// src/app/[lang]/(withoutHeader)/request-demo/components/form/index.tsx
"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { Button } from "@/components/ui/button";
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import { Checkbox } from "@/components/ui/checkbox";
import { toast } from "sonner";
import { Input } from "@/components/ui/input";
import { useEffect, useState } from "react";
import { useTranslations } from "next-intl";
import { cn } from "@/lib/utils";
import { Link, useRouter } from "@/i18n/routing";
import ToastErrorMessage from "@/components/common/toast-error-message";

const FormSchema = z.object({
  name: z.string().min(3, {
    message: "Name must be at least 3 characters.",
  }),
  email: z.string().email("This is not a valid email."),
  "job-title": z.string().min(3, {
    message: "Job title must be at least 3 characters.",
  }),
  terms: z.boolean().refine((val) => val === true),
});

export type FormSchemaType = z.infer<typeof FormSchema>;

export function RequestDemoForm({ lang }: { lang: string }) {
  const [loading, setLoading] = useState(false);
  const [submitSuccessful, setSubmitSuccessful] = useState(false);
  const router = useRouter();

  const t = useTranslations("request-demo");
  const defaultValues = {
    name: "",
    email: "",
    "job-title": "",
    terms: false,
  };

  const form = useForm<FormSchemaType>({
    resolver: zodResolver(FormSchema),
    defaultValues,
  });

  async function onSubmit(data: FormSchemaType) {
    setLoading(true);
    const targetUrl =
      lang === "en"
        ? "https://api.form-data.com/f/maxbqln43gps853piaiwy"
        : "https://api.form-data.com/f/drwe35duuwb2jjt8fuagda";
    try {
      await fetch(targetUrl, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(data),
      });
      setSubmitSuccessful(true);
      setLoading(false);
      router.push("/thank-you-for-the-demo-request");
    } catch (error) {
      setSubmitSuccessful(false);
      setLoading(false);
      toast.error(
        <ToastErrorMessage>Error while submiting the form</ToastErrorMessage>
      );
    }
  }

  useEffect(() => {
    if (submitSuccessful) {
      form.reset(defaultValues);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [submitSuccessful]);

  return (
    <div className="p-6 space-y-4 lg:space-y-6 md:p-8">
      <h1 className="text-xl font-bold leading-tight tracking-tight text-center text-black-600 md:text-2xl dark:text-white">
        {t("title")}
      </h1>
      <Form {...form}>
        <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
          <FormField
            control={form.control}
            name="name"
            render={({ field }) => (
              <FormItem>
                <FormLabel>{t("name")}</FormLabel>
                <FormControl>
                  <Input type="text" {...field} />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />

          <FormField
            control={form.control}
            name="email"
            render={({ field }) => (
              <FormItem>
                <FormLabel>{t("email")}</FormLabel>
                <FormControl>
                  <Input type="email" {...field} />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />

          <FormField
            control={form.control}
            name="job-title"
            render={({ field }) => (
              <FormItem>
                <FormLabel>{t("jobTitle")}</FormLabel>
                <FormControl>
                  <Input type="text" {...field} />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />

          <FormField
            control={form.control}
            name="terms"
            render={({ field }) => (
              <FormItem className="flex flex-row items-start space-x-3 space-y-0 ">
                <FormControl>
                  <Checkbox
                    checked={field.value}
                    onCheckedChange={field.onChange}
                  />
                </FormControl>
                <div className="space-y-1 leading-none">
                  <FormLabel className="font-light text-xs text-gray-500 dark:text-gray-300">
                    {t.rich("rule", {
                      link: (chunks) => (
                        <Link
                          className="text-primary-600 hover:underline"
                          href="/privacy-policy"
                        >
                          {chunks}
                        </Link>
                      ),
                    })}
                  </FormLabel>
                </div>
                <FormMessage />
              </FormItem>
            )}
          />
          <Button
            type="submit"
            loading={loading}
            size={"sm"}
            className={cn(
              "w-full transition ease-in-out duration-300",
              !form.formState.isValid && "opacity-25 cursor-not-allowed"
            )}
            disabled={!form.formState.isValid || loading}
          >
            {!loading && <>{t("cta")}</>}
          </Button>
        </form>
      </Form>
    </div>
  );
}

export default RequestDemoForm;

// components/FormComponent.vue
<template>
  <form class="space-y-4 lg:space-y-6 max-w-md" action="" method="post" @submit.prevent="submitForm">
    <div>
      <label
        for="name"
        class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
      ><ContentSlot :use="$slots.name" unwrap="p" /></label>
      <input
        id="name"
        v-model="formData.name"
        type="text"
        name="name"
        class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg transition ease-in-out duration-300 focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
      >
      <span v-if="v$.name.$error" class="error-alert">
        {{ v$.name.$errors[0].$message }}
      </span>
    </div>
    <div>
      <label
        for="email"
        class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
      ><ContentSlot :use="$slots.email" unwrap="p" /></label>
      <input
        id="email"
        v-model="formData.email"
        type="text"
        name="email"
        class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg transition ease-in-out duration-300 focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
        autocomplete="email"
      >
    </div>
    <span v-if="v$.email.$error" class="error-alert">
      {{ v$.email.$errors[0].$message }}
    </span>
    <div>
      <label
        for="job-title"
        class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
      ><ContentSlot :use="$slots.jobTitle" unwrap="p" /></label>
      <input
        id="job-title"
        v-model="formData.jobTitle"
        type="text"
        name="job"
        class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg transition ease-in-out duration-300 focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
      >
      <span v-if="v$.jobTitle.$error" class="error-alert">
        {{ v$.jobTitle.$errors[0].$message }}
      </span>
    </div>
    <div class="flex items-start">
      <div class="flex items-center h-5">
        <input
          id="terms"
          v-model="formData.terms"
          aria-describedby="terms"
          type="checkbox"
          class="w-4 h-4 border text-primary-600 border-gray-300 rounded bg-gray-50 focus:ring-offset-0 focus:ring-0 dark:bg-gray-700 dark:border-gray-600 focus:ring-primary-600 dark:ring-offset-gray-800"
        >
      </div>
      <div class="ml-3 error-alert">
        <div
          class="font-light text-xs text-gray-500 dark:text-gray-300"
        >
          <ContentSlot :use="$slots.rule" unwrap="p" />
        </div>
      </div>
    </div>
    <button
      type="submit"
      class="w-full text-base text-white bg-primary-600 disabled font-bold rounded-lg px-5 py-2.5 text-center transition ease-in-out duration-300 dark:bg-primary-600 hover:bg-primary-700 dark:focus:ring-primary-800"
      :class="{'opacity-25 cursor-not-allowed': !isFormValid }"
      :disabled="!isFormValid"
    >
      {{ $t('request-demo') }}
    </button>
  </form>
</template>

<script setup lang="ts">
import axios from 'axios'
import { useVuelidate } from '@vuelidate/core'
import { required, email } from '~/utils/i18n-validators'

const isSuccess = ref(false)
const loading = ref(false)

const formData = reactive({
  name: '',
  email: '',
  jobTitle: '',
  terms: false,
})

const rules = computed(() => {
  return {
    name: { required },
    email: { required, email },
    jobTitle: { required },
  }
})

const v$ = useVuelidate(rules, formData)

const isFormValid = computed(() => {
  if (formData.name && formData.email && formData.jobTitle && formData.terms) {
    return true
  } else {
    return false
  }
})

const submitForm = async () => {
  const isFormCorrect = await v$.value.$validate()
  if (isFormCorrect) {
    loading.value = true
    await axios.post('https://api.form-data.com/f/gq31layf9m65mw704tcnmm', formData)
    // @ts-ignore
    Air360.identify(formData.email)
    loading.value = false
    isSuccess.value = !isSuccess.value
    v$.value.$reset()
    Object.assign(formData, { name: '', email: '', jobTitle: '', terms: false })
  }
}
</script>

<style lang="postcss">
.error-alert {
  @apply text-xs text-red-500;
}
</style>
