// src/components/blog/related-articles.tsx
import React from "react";
import BlogCard from "@/components/blog/card";
import { allBlogs } from "contentlayer/generated";
import { getTranslations } from "@/i18n/getTranslations";

interface RelatedArticlesProps {
  lang: string;
  tags: string[];
  currentSlug: string;
}

const RelatedArticles: React.FC<RelatedArticlesProps> = async ({
  lang,
  tags,
  currentSlug,
}) => {
  const t = await getTranslations({ locale: lang, namespace: "blog" });

  const posts = allBlogs
    .filter(
      (post) =>
        post.locale === lang && // Locale match
        post.tags.some((tag) => tags.includes(tag)) && // At least one matching tag
        post.published && // Has a published date
        post.slug !== currentSlug // Different slug
    )
    .slice(0, 3); // Limit the list to 3 posts

  if (posts.length === 0) return null;

  return (
    <aside
      aria-label={t("related-articles")}
      className="py-8 lg:py-24 bg-white dark:bg-gray-900"
    >
      <div className="container">
        <h2 className="mb-8 text-2xl font-bold text-gray-900 dark:text-white">
          {t("related-articles")}
        </h2>
        <div className="grid gap-12 md:grid-cols-2 lg:grid-cols-3">
          {posts.map((post, idx) => (
            <BlogCard key={idx} post={post} />
          ))}
        </div>
      </div>
    </aside>
  );
};

export default RelatedArticles;

// components/RelatedArticles.vue
<template>
  <aside
    aria-label="Related articles"
    class="py-8 lg:py-24 bg-white dark:bg-gray-900"
  >
    <div class="px-4 mx-auto max-w-screen-[1400px] lg:px-8">
      <h2 class="mb-8 text-2xl font-bold text-gray-900 dark:text-white">
        関連記事
      </h2>
      <div class="grid gap-12 md:grid-cols-2 lg:grid-cols-3">
        <BlogCard v-for="article in data" :key="article._path" :data="article" />
      </div>
    </div>
  </aside>
</template>

<script setup lang="ts">
const { $i18n } = useNuxtApp()
const { path } = useRoute()

const { data } = await useAsyncData(`blog-${path}`, () => {
  return queryContent($i18n.locale._value, '/blog')
    .sort({ published: -1 })
    .where({ _path: { $ne: `/${$i18n.locale._value}${path}` } })
    .limit(3)
    .find()
})
</script>
