// components/Dropdowns/Items.vue
<template>
  <li class="group flex items-center justify-start">
    <NuxtLink :to="localePath(slug)" class="w-full py-3 border-b border-b-gray-200 hover:(text-primary-600 text-shadow-primary)">
      <fa-icon class="fa-lg w-6 mr-3" :class="`${textColor}`" :icon="['far', icon]" /><span class="text-sm font-bold text-black-600 group-hover:text-primary-600">{{ text }}</span>
    </NuxtLink>
  </li>
</template>

<script setup lang="ts">
const localePath = useLocalePath()

interface Props {
  slug: string
  icon: string
  text: string
  textColor: string
}

defineProps<Props>()
</script>

// src/components/layout/mobile-menu/items.tsx
import React from "react";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { IconName } from "@fortawesome/fontawesome-svg-core";
import { Link, Pathnames } from "@/i18n/routing";
import { SheetTrigger } from "@/components/ui/sheet";

interface ItemsProps {
  slug: Pathnames;
  icon: IconName;
  text: string;
  textColor?: string;
  hoverColor?: string;
  bgColor?: string;
  className?: string;
}

const Items: React.FC<ItemsProps> = ({
  slug,
  icon,
  text,
  className,
  textColor = "text-primary-600",
  hoverColor = "hover:bg-gray-75",
  // bgColor = "bg-gray-75",
}) => {
  return (
    <li className={`group flex items-center justify-start ${className}`}>
      <SheetTrigger asChild>
        <Link
          href={slug}
          className={`flex items-center w-full py-2 mb-1 rounded-xl  ${hoverColor}`}
        >
          <div
            className={`w-9 h-9 mr-2 rounded-lg flex justify-center items-center`}
          >
            <FontAwesomeIcon
              className={`fa-lg w-6 ${textColor}`}
              icon={["far", icon]}
            />
          </div>
          <span className="text-sm font-semibold text-black-600">{text}</span>
        </Link>
      </SheetTrigger>
    </li>
  );
};

export default Items;
