// src/components/layout/mobile-menu/item-block.tsx
import React, { useState } from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { IconProp } from '@fortawesome/fontawesome-svg-core';
import { Button } from '@/components/ui/button';

interface ItemBlockProps {
  title: string;
  children?: React.ReactNode;
  onToggle?: () => void;
}

const ItemBlock: React.FC<ItemBlockProps> = ({ title, children, onToggle }) => {
  const [isOpen, setIsOpen] = useState(false);

  const toggle = () => {
    setIsOpen(!isOpen);
    // Emit event if needed
    onToggle && onToggle();
  };

  return (
    <li>
      <Button variant={'ghost'} aria-expanded={isOpen} className='w-full py-3 px-0 font-bold text-black-600 text-xl flex items-center justify-between' onClick={toggle}>
        {title}
        <FontAwesomeIcon className={`fa-lg transform transition-all text-primary-600 ${isOpen ? 'rotate-180' : ''}`} icon={['far', 'angle-down'] as IconProp} />
        <span className='sr-only'>Open {title}</span>
      </Button>
      <div>{children}</div>
    </li>
  );
};

export default ItemBlock;

// components/Dropdowns/ItemBlock.vue
<template>
  <li>
    <button :aria-expanded="isOpen" class="w-full py-3 font-bold text-black-600 text-xl flex items-center justify-between" @click="toggle">
      {{ title }}<fa-icon :class="{'rotate-180': isOpen}" class="fa-lg transform transition-all text-primary-600" :icon="['far', 'angle-down']" />
      <span class="sr-only">Open mobile menu</span>
    </button>
    <div>
      <slot name="subItems" />
    </div>
  </li>
</template>

<script setup lang="ts">
interface Props {
  title: string
}

const isOpen = ref(false)

// defineEmits<{(e: 'toggle'): void}>()
const emit = defineEmits(['toggle'])

const toggle = () => {
  isOpen.value = !isOpen.value
  emit('toggle')
}

defineProps<Props>()
</script>
